### ISSUE TITLE
NUMLOCK implementation is wrong

### ISSUE THREAD

**Issue by jaygreco** [nullbitsco/tidbit#19]
#Several keymaps spam the numlock key so that the numpad always working regardless of how numlock is set on the host. This seems to be causing some other issues. Examine a different way of accomplishing this.

**Comment by hoseroony** [comment]
@jaygreco 
ok here's my potential repro so far.  I'm in my oled keymap which very slightly modified from yours, but its numlock related.
0) open notepad
1) double tap enter to head into _FUNC
2) single tap enter to head back into _BASE
3) do not press another key on the tidbit, but instead return to my main keyboard
4) type asdf over and over again on my main keyboard in notepad

this is the result I got, and I had to go press enter (although presuming any key on the tidbit will do this), to stop the repeating:

asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

**Comment by jaygreco** [comment]
Great find. Let me give it a shot and see if I can make the same thing happen! Nice work on finding the magic combo.

**Comment by hoseroony** [comment]
@jaygreco  I can no longer repro the steps above with the oled hex you provided in discord.  A step I missed in the description above is that the Toggle Keys popup shows up, and that also now does not appear.  Gotta add back my own call to that key in my version.
